spring:
  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/credit?retryWrites=true&w=majority

  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

microservices-urls:
  api-client: ${API_CLIENT_CONFIG}