spring:

  profiles:
    active: default

  data:
    mongodb:
      uri: mongodb+srv://spiritbear:Cuymagic321@mycluster.s22zz.mongodb.net/credit?retryWrites=true&w=majority


microservices-urls:
  api-client: ${API_CLIENT_CONFIG}

---
spring:

  cloud:
    config:
      activate:
        on-profile: dev

  application:
    name: creditcard-microservice

  config:
    import: optional:configserver:http://localhost:8888

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

