server:
  port: 8085
spring:
  application:
    name: bankcredit-microservice
  config:
    import: configserver:http://localhost:8887
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
