name: Build and deploy to Azure Spring Cloud

on: [push]
env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZR_CREDS.subscriptionId }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        check-latest: false
        cache: 'maven'
    - name: Build with Maven
      run: mvn package -DskipTests
    - name: Login to Azure Spring Cloud
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZR_CREDS }}
    - name: Get Subscription ID
      run: |
        echo "$(az account show --query id --output tsv --only-show-errors)"
      shell: bash
    - name: Deploy to Azure Spring Cloud
      uses: azure/spring-cloud-deploy@v1
      with:
        action: Deploy
        azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
        service-name: ${{ secrets.AZR_CREDS.serviceName }}
        app-name: ${{ secrets.AZR_CREDS.appName }}
        use-staging-deployment: false
        package: ${{ secrets.AZR_CREDS.jarFile }}
