name: Build and deploy to Azure Spring Cloud

on: [push]

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZR_CREDS.subscriptionId }}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: maven build, clean
        run: |
          mvn clean package
      - name: Login to Azure Spring Cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZR_CREDS }}

      - name: deploy to production with artifact
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: ${{ secrets.AZR_CREDS['subscriptionId'] }}
          action: Deploy
          service-name: azurespringboot2022
          app-name: creditmicroservice
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}
